Set verbose = 1;
INSERT INTO Countries SET Id = 1, Code = "AD", Name = "Andorra";
INSERT INTO Countries SET Id = 2, Code = "AE", Name = "United Arab Emirates";
INSERT INTO Countries SET Id = 3, Code = "AF", Name = "Afghanistan";
INSERT INTO Countries SET Id = 4, Code = "AG", Name = "Antigua and Barbuda";
INSERT INTO Countries SET Id = 5, Code = "AI", Name = "Anguilla";
INSERT INTO Countries SET Id = 6, Code = "AL", Name = "Albania";
INSERT INTO Countries SET Id = 7, Code = "AM", Name = "Armenia";
INSERT INTO Countries SET Id = 8, Code = "AO", Name = "Angola";
INSERT INTO Countries SET Id = 9, Code = "AQ", Name = "Antarctica";
INSERT INTO Countries SET Id = 10, Code = "AR", Name = "Argentina";
INSERT INTO Countries SET Id = 11, Code = "AS", Name = "American Samoa";
INSERT INTO Countries SET Id = 12, Code = "AT", Name = "Austria";
INSERT INTO Countries SET Id = 13, Code = "AU", Name = "Australia";
INSERT INTO Countries SET Id = 14, Code = "AW", Name = "Aruba";
INSERT INTO Countries SET Id = 15, Code = "AX", Name = "Åland Islands";
INSERT INTO Countries SET Id = 16, Code = "AZ", Name = "Azerbaijan";
INSERT INTO Countries SET Id = 17, Code = "BA", Name = "Bosnia and Herzegovina";
INSERT INTO Countries SET Id = 18, Code = "BB", Name = "Barbados";
INSERT INTO Countries SET Id = 19, Code = "BD", Name = "Bangladesh";
INSERT INTO Countries SET Id = 20, Code = "BE", Name = "Belgium";
INSERT INTO Countries SET Id = 21, Code = "BF", Name = "Burkina Faso";
INSERT INTO Countries SET Id = 22, Code = "BG", Name = "Bulgaria";
INSERT INTO Countries SET Id = 23, Code = "BH", Name = "Bahrain";
INSERT INTO Countries SET Id = 24, Code = "BI", Name = "Burundi";
INSERT INTO Countries SET Id = 25, Code = "BJ", Name = "Benin";
INSERT INTO Countries SET Id = 26, Code = "BL", Name = "Saint Barthélemy";
INSERT INTO Countries SET Id = 27, Code = "BM", Name = "Bermuda";
INSERT INTO Countries SET Id = 28, Code = "BN", Name = "Brunei Darussalam";
INSERT INTO Countries SET Id = 29, Code = "BO", Name = "Bolivia";
INSERT INTO Countries SET Id = 30, Code = "BQ", Name = "Caribbean Netherlands ";
INSERT INTO Countries SET Id = 31, Code = "BR", Name = "Brazil";
INSERT INTO Countries SET Id = 32, Code = "BS", Name = "Bahamas";
INSERT INTO Countries SET Id = 33, Code = "BT", Name = "Bhutan";
INSERT INTO Countries SET Id = 34, Code = "BV", Name = "Bouvet Island";
INSERT INTO Countries SET Id = 35, Code = "BW", Name = "Botswana";
INSERT INTO Countries SET Id = 36, Code = "BY", Name = "Belarus";
INSERT INTO Countries SET Id = 37, Code = "BZ", Name = "Belize";
INSERT INTO Countries SET Id = 38, Code = "CA", Name = "Canada";
INSERT INTO Countries SET Id = 39, Code = "CC", Name = "Cocos (Keeling) Islands";
INSERT INTO Countries SET Id = 40, Code = "CD", Name = "Congo";
INSERT INTO Countries SET Id = 41, Code = "CF", Name = "Central African Republic";
INSERT INTO Countries SET Id = 42, Code = "CG", Name = "Congo";
INSERT INTO Countries SET Id = 43, Code = "CH", Name = "Switzerland";
INSERT INTO Countries SET Id = 44, Code = "CI", Name = "Côte d'Ivoire";
INSERT INTO Countries SET Id = 45, Code = "CK", Name = "Cook Islands";
INSERT INTO Countries SET Id = 46, Code = "CL", Name = "Chile";
INSERT INTO Countries SET Id = 47, Code = "CM", Name = "Cameroon";
INSERT INTO Countries SET Id = 48, Code = "CN", Name = "China";
INSERT INTO Countries SET Id = 49, Code = "CO", Name = "Colombia";
INSERT INTO Countries SET Id = 50, Code = "CR", Name = "Costa Rica";
INSERT INTO Countries SET Id = 51, Code = "CU", Name = "Cuba";
INSERT INTO Countries SET Id = 52, Code = "CV", Name = "Cape Verde";
INSERT INTO Countries SET Id = 53, Code = "CW", Name = "Curaçao";
INSERT INTO Countries SET Id = 54, Code = "CX", Name = "Christmas Island";
INSERT INTO Countries SET Id = 55, Code = "CY", Name = "Cyprus";
INSERT INTO Countries SET Id = 56, Code = "CZ", Name = "Czech Republic";
INSERT INTO Countries SET Id = 57, Code = "DE", Name = "Germany";
INSERT INTO Countries SET Id = 58, Code = "DJ", Name = "Djibouti";
INSERT INTO Countries SET Id = 59, Code = "DK", Name = "Denmark";
INSERT INTO Countries SET Id = 60, Code = "DM", Name = "Dominica";
INSERT INTO Countries SET Id = 61, Code = "DO", Name = "Dominican Republic";
INSERT INTO Countries SET Id = 62, Code = "DZ", Name = "Algeria";
INSERT INTO Countries SET Id = 63, Code = "EC", Name = "Ecuador";
INSERT INTO Countries SET Id = 64, Code = "EE", Name = "Estonia";
INSERT INTO Countries SET Id = 65, Code = "EG", Name = "Egypt";
INSERT INTO Countries SET Id = 66, Code = "EH", Name = "Western Sahara";
INSERT INTO Countries SET Id = 67, Code = "ER", Name = "Eritrea";
INSERT INTO Countries SET Id = 68, Code = "ES", Name = "Spain";
INSERT INTO Countries SET Id = 69, Code = "ET", Name = "Ethiopia";
INSERT INTO Countries SET Id = 70, Code = "FI", Name = "Finland";
INSERT INTO Countries SET Id = 71, Code = "FJ", Name = "Fiji";
INSERT INTO Countries SET Id = 72, Code = "FK", Name = "Falkland Islands";
INSERT INTO Countries SET Id = 73, Code = "FM", Name = "Micronesia";
INSERT INTO Countries SET Id = 74, Code = "FO", Name = "Faroe Islands";
INSERT INTO Countries SET Id = 75, Code = "FR", Name = "France";
INSERT INTO Countries SET Id = 76, Code = "GA", Name = "Gabon";
INSERT INTO Countries SET Id = 77, Code = "GB", Name = "United Kingdom";
INSERT INTO Countries SET Id = 78, Code = "GD", Name = "Grenada";
INSERT INTO Countries SET Id = 79, Code = "GE", Name = "Georgia";
INSERT INTO Countries SET Id = 80, Code = "GF", Name = "French Guiana";
INSERT INTO Countries SET Id = 81, Code = "GG", Name = "Guernsey";
INSERT INTO Countries SET Id = 82, Code = "GH", Name = "Ghana";
INSERT INTO Countries SET Id = 83, Code = "GI", Name = "Gibraltar";
INSERT INTO Countries SET Id = 84, Code = "GL", Name = "Greenland";
INSERT INTO Countries SET Id = 85, Code = "GM", Name = "Gambia";
INSERT INTO Countries SET Id = 86, Code = "GN", Name = "Guinea";
INSERT INTO Countries SET Id = 87, Code = "GP", Name = "Guadeloupe";
INSERT INTO Countries SET Id = 88, Code = "GQ", Name = "Equatorial Guinea";
INSERT INTO Countries SET Id = 89, Code = "GR", Name = "Greece";
INSERT INTO Countries SET Id = 90, Code = "GS", Name = "South Georgia and the South Sandwich Islands";
INSERT INTO Countries SET Id = 91, Code = "GT", Name = "Guatemala";
INSERT INTO Countries SET Id = 92, Code = "GU", Name = "Guam";
INSERT INTO Countries SET Id = 93, Code = "GW", Name = "Guinea-Bissau";
INSERT INTO Countries SET Id = 94, Code = "GY", Name = "Guyana";
INSERT INTO Countries SET Id = 95, Code = "HK", Name = "Hong Kong";
INSERT INTO Countries SET Id = 96, Code = "HM", Name = "Heard and McDonald Islands";
INSERT INTO Countries SET Id = 97, Code = "HN", Name = "Honduras";
INSERT INTO Countries SET Id = 98, Code = "HR", Name = "Croatia";
INSERT INTO Countries SET Id = 99, Code = "HT", Name = "Haiti";
INSERT INTO Countries SET Id = 100, Code = "HU", Name = "Hungary";
INSERT INTO Countries SET Id = 101, Code = "ID", Name = "Indonesia";
INSERT INTO Countries SET Id = 102, Code = "IE", Name = "Ireland";
INSERT INTO Countries SET Id = 103, Code = "IL", Name = "Israel";
INSERT INTO Countries SET Id = 104, Code = "IM", Name = "Isle of Man";
INSERT INTO Countries SET Id = 105, Code = "IN", Name = "India";
INSERT INTO Countries SET Id = 106, Code = "IO", Name = "British Indian Ocean Territory";
INSERT INTO Countries SET Id = 107, Code = "IQ", Name = "Iraq";
INSERT INTO Countries SET Id = 108, Code = "IR", Name = "Iran";
INSERT INTO Countries SET Id = 109, Code = "IS", Name = "Iceland";
INSERT INTO Countries SET Id = 110, Code = "IT", Name = "Italy";
INSERT INTO Countries SET Id = 111, Code = "JE", Name = "Jersey";
INSERT INTO Countries SET Id = 112, Code = "JM", Name = "Jamaica";
INSERT INTO Countries SET Id = 113, Code = "JO", Name = "Jordan";
INSERT INTO Countries SET Id = 114, Code = "JP", Name = "Japan";
INSERT INTO Countries SET Id = 115, Code = "KE", Name = "Kenya";
INSERT INTO Countries SET Id = 116, Code = "KG", Name = "Kyrgyzstan";
INSERT INTO Countries SET Id = 117, Code = "KH", Name = "Cambodia";
INSERT INTO Countries SET Id = 118, Code = "KI", Name = "Kiribati";
INSERT INTO Countries SET Id = 119, Code = "KM", Name = "Comoros";
INSERT INTO Countries SET Id = 120, Code = "KN", Name = "Saint Kitts and Nevis";
INSERT INTO Countries SET Id = 121, Code = "KP", Name = "North Korea";
INSERT INTO Countries SET Id = 122, Code = "KR", Name = "South Korea";
INSERT INTO Countries SET Id = 123, Code = "KW", Name = "Kuwait";
INSERT INTO Countries SET Id = 124, Code = "KY", Name = "Cayman Islands";
INSERT INTO Countries SET Id = 125, Code = "KZ", Name = "Kazakhstan";
INSERT INTO Countries SET Id = 126, Code = "LA", Name = "Lao People's Democratic Republic";
INSERT INTO Countries SET Id = 127, Code = "LB", Name = "Lebanon";
INSERT INTO Countries SET Id = 128, Code = "LC", Name = "Saint Lucia";
INSERT INTO Countries SET Id = 129, Code = "LI", Name = "Liechtenstein";
INSERT INTO Countries SET Id = 130, Code = "LK", Name = "Sri Lanka";
INSERT INTO Countries SET Id = 131, Code = "LR", Name = "Liberia";
INSERT INTO Countries SET Id = 132, Code = "LS", Name = "Lesotho";
INSERT INTO Countries SET Id = 133, Code = "LT", Name = "Lithuania";
INSERT INTO Countries SET Id = 134, Code = "LU", Name = "Luxembourg";
INSERT INTO Countries SET Id = 135, Code = "LV", Name = "Latvia";
INSERT INTO Countries SET Id = 136, Code = "LY", Name = "Libya";
INSERT INTO Countries SET Id = 137, Code = "MA", Name = "Morocco";
INSERT INTO Countries SET Id = 138, Code = "MC", Name = "Monaco";
INSERT INTO Countries SET Id = 139, Code = "MD", Name = "Moldova";
INSERT INTO Countries SET Id = 140, Code = "ME", Name = "Montenegro";
INSERT INTO Countries SET Id = 141, Code = "MF", Name = "Saint-Martin (France)";
INSERT INTO Countries SET Id = 142, Code = "MG", Name = "Madagascar";
INSERT INTO Countries SET Id = 143, Code = "MH", Name = "Marshall Islands";
INSERT INTO Countries SET Id = 144, Code = "MK", Name = "Macedonia";
INSERT INTO Countries SET Id = 145, Code = "ML", Name = "Mali";
INSERT INTO Countries SET Id = 146, Code = "MM", Name = "Myanmar";
INSERT INTO Countries SET Id = 147, Code = "MN", Name = "Mongolia";
INSERT INTO Countries SET Id = 148, Code = "MO", Name = "Macau";
INSERT INTO Countries SET Id = 149, Code = "MP", Name = "Northern Mariana Islands";
INSERT INTO Countries SET Id = 150, Code = "MQ", Name = "Martinique";
INSERT INTO Countries SET Id = 151, Code = "MR", Name = "Mauritania";
INSERT INTO Countries SET Id = 152, Code = "MS", Name = "Montserrat";
INSERT INTO Countries SET Id = 153, Code = "MT", Name = "Malta";
INSERT INTO Countries SET Id = 154, Code = "MU", Name = "Mauritius";
INSERT INTO Countries SET Id = 155, Code = "MV", Name = "Maldives";
INSERT INTO Countries SET Id = 156, Code = "MW", Name = "Malawi";
INSERT INTO Countries SET Id = 157, Code = "MX", Name = "Mexico";
INSERT INTO Countries SET Id = 158, Code = "MY", Name = "Malaysia";
INSERT INTO Countries SET Id = 159, Code = "MZ", Name = "Mozambique";
INSERT INTO Countries SET Id = 160, Code = "NA", Name = "Namibia";
INSERT INTO Countries SET Id = 161, Code = "NC", Name = "New Caledonia";
INSERT INTO Countries SET Id = 162, Code = "NE", Name = "Niger";
INSERT INTO Countries SET Id = 163, Code = "NF", Name = "Norfolk Island";
INSERT INTO Countries SET Id = 164, Code = "NG", Name = "Nigeria";
INSERT INTO Countries SET Id = 165, Code = "NI", Name = "Nicaragua";
INSERT INTO Countries SET Id = 166, Code = "NL", Name = "The Netherlands";
INSERT INTO Countries SET Id = 167, Code = "NO", Name = "Norway";
INSERT INTO Countries SET Id = 168, Code = "NP", Name = "Nepal";
INSERT INTO Countries SET Id = 169, Code = "NR", Name = "Nauru";
INSERT INTO Countries SET Id = 170, Code = "NU", Name = "Niue";
INSERT INTO Countries SET Id = 171, Code = "NZ", Name = "New Zealand";
INSERT INTO Countries SET Id = 172, Code = "OM", Name = "Oman";
INSERT INTO Countries SET Id = 173, Code = "PA", Name = "Panama";
INSERT INTO Countries SET Id = 174, Code = "PE", Name = "Peru";
INSERT INTO Countries SET Id = 175, Code = "PF", Name = "French Polynesia";
INSERT INTO Countries SET Id = 176, Code = "PG", Name = "Papua New Guinea";
INSERT INTO Countries SET Id = 177, Code = "PH", Name = "Philippines";
INSERT INTO Countries SET Id = 178, Code = "PK", Name = "Pakistan";
INSERT INTO Countries SET Id = 179, Code = "PL", Name = "Poland";
INSERT INTO Countries SET Id = 180, Code = "PM", Name = "St. Pierre and Miquelon";
INSERT INTO Countries SET Id = 181, Code = "PN", Name = "Pitcairn";
INSERT INTO Countries SET Id = 182, Code = "PR", Name = "Puerto Rico";
INSERT INTO Countries SET Id = 183, Code = "PS", Name = "Palestine";
INSERT INTO Countries SET Id = 184, Code = "PT", Name = "Portugal";
INSERT INTO Countries SET Id = 185, Code = "PW", Name = "Palau";
INSERT INTO Countries SET Id = 186, Code = "PY", Name = "Paraguay";
INSERT INTO Countries SET Id = 187, Code = "QA", Name = "Qatar";
INSERT INTO Countries SET Id = 188, Code = "RE", Name = "Réunion";
INSERT INTO Countries SET Id = 189, Code = "RO", Name = "Romania";
INSERT INTO Countries SET Id = 190, Code = "RS", Name = "Serbia";
INSERT INTO Countries SET Id = 191, Code = "RU", Name = "Russian Federation";
INSERT INTO Countries SET Id = 192, Code = "RW", Name = "Rwanda";
INSERT INTO Countries SET Id = 193, Code = "SA", Name = "Saudi Arabia";
INSERT INTO Countries SET Id = 194, Code = "SB", Name = "Solomon Islands";
INSERT INTO Countries SET Id = 195, Code = "SC", Name = "Seychelles";
INSERT INTO Countries SET Id = 196, Code = "SD", Name = "Sudan";
INSERT INTO Countries SET Id = 197, Code = "SE", Name = "Sweden";
INSERT INTO Countries SET Id = 198, Code = "SG", Name = "Singapore";
INSERT INTO Countries SET Id = 199, Code = "SH", Name = "Saint Helena";
INSERT INTO Countries SET Id = 200, Code = "SI", Name = "Slovenia";
INSERT INTO Countries SET Id = 201, Code = "SJ", Name = "Svalbard and Jan Mayen Islands";
INSERT INTO Countries SET Id = 202, Code = "SK", Name = "Slovakia";
INSERT INTO Countries SET Id = 203, Code = "SL", Name = "Sierra Leone";
INSERT INTO Countries SET Id = 204, Code = "SM", Name = "San Marino";
INSERT INTO Countries SET Id = 205, Code = "SN", Name = "Senegal";
INSERT INTO Countries SET Id = 206, Code = "SO", Name = "Somalia";
INSERT INTO Countries SET Id = 207, Code = "SR", Name = "Suriname";
INSERT INTO Countries SET Id = 208, Code = "SS", Name = "South Sudan";
INSERT INTO Countries SET Id = 209, Code = "ST", Name = "Sao Tome and Principe";
INSERT INTO Countries SET Id = 210, Code = "SV", Name = "El Salvador";
INSERT INTO Countries SET Id = 211, Code = "SX", Name = "Sint Maarten (Dutch part)";
INSERT INTO Countries SET Id = 212, Code = "SY", Name = "Syria";
INSERT INTO Countries SET Id = 213, Code = "SZ", Name = "Swaziland";
INSERT INTO Countries SET Id = 214, Code = "TC", Name = "Turks and Caicos Islands";
INSERT INTO Countries SET Id = 215, Code = "TD", Name = "Chad";
INSERT INTO Countries SET Id = 216, Code = "TF", Name = "French Southern Territories";
INSERT INTO Countries SET Id = 217, Code = "TG", Name = "Togo";
INSERT INTO Countries SET Id = 218, Code = "TH", Name = "Thailand";
INSERT INTO Countries SET Id = 219, Code = "TJ", Name = "Tajikistan";
INSERT INTO Countries SET Id = 220, Code = "TK", Name = "Tokelau";
INSERT INTO Countries SET Id = 221, Code = "TL", Name = "Timor-Leste";
INSERT INTO Countries SET Id = 222, Code = "TM", Name = "Turkmenistan";
INSERT INTO Countries SET Id = 223, Code = "TN", Name = "Tunisia";
INSERT INTO Countries SET Id = 224, Code = "TO", Name = "Tonga";
INSERT INTO Countries SET Id = 225, Code = "TR", Name = "Turkey";
INSERT INTO Countries SET Id = 226, Code = "TT", Name = "Trinidad and Tobago";
INSERT INTO Countries SET Id = 227, Code = "TV", Name = "Tuvalu";
INSERT INTO Countries SET Id = 228, Code = "TW", Name = "Taiwan";
INSERT INTO Countries SET Id = 229, Code = "TZ", Name = "Tanzania";
INSERT INTO Countries SET Id = 230, Code = "UA", Name = "Ukraine";
INSERT INTO Countries SET Id = 231, Code = "UG", Name = "Uganda";
INSERT INTO Countries SET Id = 232, Code = "UM", Name = "United States Minor Outlying Islands";
INSERT INTO Countries SET Id = 233, Code = "US", Name = "United States";
INSERT INTO Countries SET Id = 234, Code = "UY", Name = "Uruguay";
INSERT INTO Countries SET Id = 235, Code = "UZ", Name = "Uzbekistan";
INSERT INTO Countries SET Id = 236, Code = "VA", Name = "Vatican";
INSERT INTO Countries SET Id = 237, Code = "VC", Name = "Saint Vincent and the Grenadines";
INSERT INTO Countries SET Id = 238, Code = "VE", Name = "Venezuela";
INSERT INTO Countries SET Id = 239, Code = "VG", Name = "Virgin Islands (British)";
INSERT INTO Countries SET Id = 240, Code = "VI", Name = "Virgin Islands (U.S.)";
INSERT INTO Countries SET Id = 241, Code = "VN", Name = "Vietnam";
INSERT INTO Countries SET Id = 242, Code = "VU", Name = "Vanuatu";
INSERT INTO Countries SET Id = 243, Code = "WF", Name = "Wallis and Futuna Islands";
INSERT INTO Countries SET Id = 244, Code = "WS", Name = "Samoa";
INSERT INTO Countries SET Id = 245, Code = "YE", Name = "Yemen";
INSERT INTO Countries SET Id = 246, Code = "YT", Name = "Mayotte";
INSERT INTO Countries SET Id = 247, Code = "ZA", Name = "South Africa";
INSERT INTO Countries SET Id = 248, Code = "ZM", Name = "Zambia";
INSERT INTO Countries SET Id = 249, Code = "ZW", Name = "Zimbabwe";